# Generated by Django 5.2.17 on 2026-08-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(db_index=True, max_length=100)),
                ('market', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('min_price', models.FloatField(help_text='Minimum price in currency/unit')),
                ('max_price', models.FloatField(help_text='Maximum price in currency/unit')),
                ('modal_price', models.FloatField(help_text='Modal (most frequent) price in currency/unit')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('unit', models.CharField(default='quintal', max_length=50)),
                ('source', models.CharField(default='data.gov.in / AGMARKNET', max_length=200)),
                ('price_date', models.DateField(help_text='The date of arrival / reporting of the price')),
                ('fetched_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this price was saved/updated in cache')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
                'ordering': ['-price_date', '-fetched_at'],
                'indexes': [models.Index(fields=['crop', 'state', 'district', 'price_date'], name='market_mark_crop_40bcf6_idx')],
            },
        ),
    ]
