# Generated by Django 5.2.17 on 2026-08-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('ideal_temperature_min', models.FloatField(blank=True, help_text='°C', null=True)),
                ('ideal_temperature_max', models.FloatField(blank=True, help_text='°C', null=True)),
                ('ideal_ph_min', models.FloatField(blank=True, null=True)),
                ('ideal_ph_max', models.FloatField(blank=True, null=True)),
                ('ideal_rainfall_min', models.FloatField(blank=True, help_text='mm/year', null=True)),
                ('ideal_rainfall_max', models.FloatField(blank=True, help_text='mm/year', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['name'],
            },
        ),
    ]
